// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9xcgw_ztfwCQD5XtxDWL4FYE-QDndaZE',
    appId: '1:121150012417:web:0f70f6b165b3a4fdaf1400',
    messagingSenderId: '121150012417',
    projectId: 'vitalia-health',
    authDomain: 'vitalia-health.firebaseapp.com',
    storageBucket: 'vitalia-health.firebasestorage.app',
    measurementId: 'G-KMM8BBP1ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonImLxMIiWF72UnwRnH77GN2uFoapS0Q',
    appId: '1:121150012417:android:3510c332cde0838caf1400',
    messagingSenderId: '121150012417',
    projectId: 'vitalia-health',
    storageBucket: 'vitalia-health.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9xcgw_ztfwCQD5XtxDWL4FYE-QDndaZE',
    appId: '1:121150012417:web:1a87a54562188955af1400',
    messagingSenderId: '121150012417',
    projectId: 'vitalia-health',
    authDomain: 'vitalia-health.firebaseapp.com',
    storageBucket: 'vitalia-health.firebasestorage.app',
    measurementId: 'G-VPGESCF1K7',
  );
}
